
import type { Race } from './types';

export const RACES_DATA: Race[] = [
  {
    id: 'maratona-do-rio-de-janeiro',
    name: 'Maratona do Rio de Janeiro',
    date: '2024-10-26',
    location: 'Rio de Janeiro, RJ',
    distance: '5k, 10k, 21k, 42k',
    description: 'Corra com uma das vistas mais bonitas do mundo como seu cenário.',
    longDescription: 'A Maratona do Rio é um festival de corridas de rua que celebra o esporte e a Cidade Maravilhosa. Com percursos que passam pelos principais cartões postais, oferece uma experiência inesquecível para atletas de todos os níveis. Além da maratona, o evento inclui meia maratona, 10k e 5k, reunindo milhares de corredores em um fim de semana de superação e alegria.',
    image: 'rio-marathon',
    featured: true,
    organizerId: 'default-organizer',
    options: [
      { distance: '5km', lots: [{ name: '1º Lote', price: 120, startDate: '2024-08-01', endDate: '2024-09-30' }] },
      { distance: '10km', lots: [{ name: '1º Lote', price: 150, startDate: '2024-08-01', endDate: '2024-09-30' }] },
      { distance: '21km (Meia Maratona)', lots: [{ name: '1º Lote', price: 200, startDate: '2024-08-01', endDate: '2024-09-30' }] },
      { distance: '42km (Maratona)', lots: [{ name: '1º Lote', price: 250, startDate: '2024-08-01', endDate: '2024-09-30' }] },
    ],
  },
  {
    id: 'corrida-de-sao-silvestre',
    name: 'Corrida de São Silvestre',
    date: '2024-12-31',
    location: 'São Paulo, SP',
    distance: '15k',
    description: 'A mais tradicional corrida de rua do Brasil, celebrando o novo ano.',
    longDescription: 'Desde 1925, a Corrida Internacional de São Silvestre fecha o ano esportivo no Brasil. O percurso de 15km passa por pontos icônicos de São Paulo, como a Avenida Paulista. É uma prova desafiadora e festiva, que atrai atletas de elite e amadores de todo o mundo para uma celebração única no último dia do ano.',
    image: 'sao-silvestre',
    featured: true,
    organizerId: 'default-organizer',
    options: [{ distance: '15km', lots: [{ name: 'Lote Único', price: 220, startDate: '2024-10-01', endDate: '2024-12-15' }] }],
  },
  {
    id: 'meia-maratona-de-florianopolis',
    name: 'Meia Maratona de Florianópolis',
    date: '2024-11-15',
    location: 'Florianópolis, SC',
    distance: '5k, 10k, 21k',
    description: 'Desafie-se na Ilha da Magia com percursos rápidos e planos.',
    longDescription: 'A Meia Maratona de Florianópolis é conhecida por seu percurso rápido e plano, ideal para quem busca quebrar recordes pessoais. A corrida oferece vistas deslumbrantes da ilha, combinando performance e beleza natural. Com opções de 5k e 10k, o evento é perfeito para toda a família de corredores.',
    image: 'florianopolis-half-marathon',
    featured: true,
    organizerId: 'default-organizer',
    options: [
      { distance: '5km', lots: [{ name: '1º Lote', price: 110, startDate: '2024-09-01', endDate: '2024-10-31' }] },
      { distance: '10km', lots: [{ name: '1º Lote', price: 140, startDate: '2024-09-01', endDate: '2024-10-31' }] },
      { distance: '21km (Meia Maratona)', lots: [{ name: '1º Lote', price: 190, startDate: '2024-09-01', endDate: '2024-10-31' }] },
    ],
  },
  {
    id: 'corrida-das-pontes-do-recife',
    name: 'Corrida das Pontes do Recife',
    date: '2025-03-23',
    location: 'Recife, PE',
    distance: '10k',
    description: 'Explore a "Veneza Brasileira" correndo por suas históricas pontes.',
    longDescription: 'A Corrida das Pontes do Recife é um convite para explorar a história e a cultura da "Veneza Brasileira" de uma forma única. O percurso de 10km cruza diversas pontes icônicas da cidade, oferecendo uma perspectiva diferente de seus rios e arquitetura. É uma prova charmosa e cheia de energia.',
    image: 'recife-bridges-race',
    featured: false,
    organizerId: 'default-organizer',
    options: [{ distance: '10km', lots: [{ name: 'Lote de Lançamento', price: 135, startDate: '2025-01-01', endDate: '2025-02-28' }] }],
  },
  {
    id: 'volta-internacional-da-pampulha',
    name: 'Volta Internacional da Pampulha',
    date: '2024-12-08',
    location: 'Belo Horizonte, MG',
    distance: '18k',
    description: 'Contorne a Lagoa da Pampulha, patrimônio da UNESCO.',
    longDescription: 'Uma das corridas mais queridas do calendário nacional, a Volta Internacional da Pampulha oferece um percurso de quase 18km ao redor da Lagoa da Pampulha, um complexo arquitetônico projetado por Oscar Niemeyer e patrimônio da UNESCO. A prova é um verdadeiro teste de resistência com a beleza de BH como recompensa.',
    image: 'pampulha-race',
    featured: false,
    organizerId: 'default-organizer',
    options: [{ distance: '18km', lots: [{ name: 'Lote Único', price: 180, startDate: '2024-10-01', endDate: '2024-11-30' }] }],
  },
  {
    id: 'maratona-de-curitiba',
    name: 'Maratona de Curitiba',
    date: '2024-11-17',
    location: 'Curitiba, PR',
    distance: '5k, 10k, 42k',
    description: 'Corra pela capital ecológica do Brasil em uma prova desafiadora.',
    longDescription: 'A Maratona de Curitiba é conhecida por seu percurso desafiador com algumas subidas, mas que recompensa os atletas com a beleza de uma das cidades mais verdes do país. Passando por parques e bairros charmosos, a prova é um evento completo para quem ama correr e apreciar a natureza urbana.',
    image: 'curitiba-marathon',
    featured: false,
    organizerId: 'default-organizer',
    options: [
      { distance: '5km', lots: [{ name: '1º Lote', price: 100, startDate: '2024-09-01', endDate: '2024-10-31' }] },
      { distance: '10km', lots: [{ name: '1º Lote', price: 130, startDate: '2024-09-01', endDate: '2024-10-31' }] },
      { distance: '42km (Maratona)', lots: [{ name: '1º Lote', price: 230, startDate: '2024-09-01', endDate: '2024-10-31' }] },
    ],
  },
];
